# Generated by Django 2.1.2 on 2018-10-02 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='userlikepost',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='userlikepost',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='UserLikePost',
        ),
    ]
